In [6]:
import json
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [15]:
def create_statistics_df(json_files):
    dfj_times = []
    mtz_times = []

    dfj_size_1 = []
    mtz_size_1 = []
    dfj_size_2 = []
    mtz_size_2 = []

    # each file contains one execution
    for file in json_files:
        with open(file, "r") as f:
            execution = json.load(f)

        dfj_times.append(execution["dfj_time_ms"])
        mtz_times.append(execution["mtz_time_ms"])

        dfj_size_1.append(execution["dfj_size_bytes_1"])
        mtz_size_1.append(execution["mtz_size_bytes_1"])

        dfj_size_2.append(execution["dfj_size_bytes_2"])
        mtz_size_2.append(execution["mtz_size_bytes_2"])

    rows = []

    for algorithm, times, size_1, size_2 in [
        ("DFJ", dfj_times, dfj_size_1, dfj_size_2),
        ("MTZ", mtz_times, mtz_size_1, mtz_size_2)
    ]:
        time_series = pd.Series(times)
        size_1_series = pd.Series(size_1)
        size_2_series = pd.Series(size_2)

        avg_time = time_series.mean()
        std_time = time_series.std()

        cv = (std_time / avg_time) * 100 if avg_time != 0 else None

        rows.append({
            "algorithm": algorithm,
            "average_time_ms": round(avg_time, 2),
            "std_time_ms": round(std_time, 2),
            "coefficient_of_variation_percent": round(cv, 2),
            "average_size_kb": round(size_1_series.mean() / 1000, 2),
            "std_size_kb": round(size_1_series.std() / 1000, 2),
            "number_of_runs": len(times)
        })

    stats_df = pd.DataFrame(rows)

    return stats_df

## Western Sahara

In [16]:
data_dir = Path("results")

json_data = {}

for file in data_dir.rglob("western_sahara*.json"):
    with open(file, "r", encoding="utf-8") as f:
        json_data[str(file)] = json.load(f)

create_statistics_df(json_data)

,algorithm,average_time_ms,std_time_ms,coefficient_of_variation_percent,average_size_kb,std_size_kb,number_of_runs
0,DFJ,97.98,1.34,1.37,829.75,0.11,5
1,MTZ,45.87,0.33,0.73,5678.97,0.11,5

## Djibouti

In [17]:
data_dir = Path("results")

json_data = {}

for file in data_dir.rglob("djibouti*.json"):
    with open(file, "r", encoding="utf-8") as f:
        json_data[str(file)] = json.load(f)

create_statistics_df(json_data)

,algorithm,average_time_ms,std_time_ms,coefficient_of_variation_percent,average_size_kb,std_size_kb,number_of_runs
0,DFJ,104.22,1.75,1.68,1531.71,0.12,5
1,MTZ,124.91,1.25,1.00,16611.75,0.12,5

## Qatar

In [18]:
data_dir = Path("results")

json_data = {}

for file in data_dir.rglob("qatar*.json"):
    with open(file, "r", encoding="utf-8") as f:
        json_data[str(file)] = json.load(f)

create_statistics_df(json_data)

,algorithm,average_time_ms,std_time_ms,coefficient_of_variation_percent,average_size_kb,std_size_kb,number_of_runs
0,DFJ,171002.70,6228.78,3.64,185175.32,0.05,5
1,MTZ,88988.26,1572.70,1.77,11282961.66,0.05,5